name: Natural Medicine
favicon: null
layout_spectrum: 0.2843035841360688
typography_spectrum: 0.12626520171761513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06782951019704342
  lightness: 0.4072398191783577
  saturation: 0.2698889223393053
  rhythmicContrast: 0.6710231185425073
purpose: []
